// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['WEB_API_KEY']!,
    appId: '1:809457563710:web:c8569ad5dc68b5333bb96f',
    messagingSenderId: '809457563710',
    projectId: 'office-dx-ad8a3',
    authDomain: 'office-dx-ad8a3.firebaseapp.com',
    storageBucket: 'office-dx-ad8a3.appspot.com',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['ANDROID_API_KEY']!,
    appId: '1:809457563710:android:8f02ddad185c54fa3bb96f',
    messagingSenderId: '809457563710',
    projectId: 'office-dx-ad8a3',
    storageBucket: 'office-dx-ad8a3.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['IOS_API_KEY']!,
    appId: '1:809457563710:ios:7aaf92742ccc358f3bb96f',
    messagingSenderId: '809457563710',
    projectId: 'office-dx-ad8a3',
    storageBucket: 'office-dx-ad8a3.appspot.com',
    iosBundleId: 'com.example.officeDx',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['MACOS_API_KEY']!,
    appId: '1:809457563710:ios:7aaf92742ccc358f3bb96f',
    messagingSenderId: '809457563710',
    projectId: 'office-dx-ad8a3',
    storageBucket: 'office-dx-ad8a3.appspot.com',
    iosBundleId: 'com.example.officeDx',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['WINDOWS_API_KEY']!,
    appId: '1:809457563710:web:f9dc57aa7bb3457d3bb96f',
    messagingSenderId: '809457563710',
    projectId: 'office-dx-ad8a3',
    authDomain: 'office-dx-ad8a3.firebaseapp.com',
    storageBucket: 'office-dx-ad8a3.appspot.com',
  );

}